name: C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prepare
      run: mkdir -p _build && cd _build
    - name: cmake
      run: cd _build && cmake ..
    - name: make
      run: cd _build && make -j $(nproc)
