name: C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install-deps
      run: |
        sudo apt-get install -y curl
        sudo apt-get install -y ca-certificates doxygen $(curl https://raw.githubusercontent.com/facebookincubator/LogDevice/master/logdevice/build_tools/ubuntu.deps)
    - name: prepare
      run: mkdir -p _build && cd _build
    - name: cmake
      run: cd _build && cmake ..
    - name: make
      run: cd _build && make -j $(nproc)
